@baseUrl = http://localhost:3000

### Replace @token with token received after logging in
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlhdCI6MTc0Nzg2OTcwNiwiZXhwIjoxNzQ3ODcyNzA2fQ.uUwZK2B48zJddeXiLquC9YKLOygycczYZpuXY4MkU6A

### Login as a driver
POST {{baseUrl}}/login 
Content-Type: application/json

{
  "username":"driverone",
  "password":"demo"
}

### Update driver's current location
POST {{baseUrl}}/driver/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "latitude": 70,
  "longitude": 0
}
### Refresh the driver's token
POST {{baseUrl}}/driver/refresh-token
Content-Type: application/json

{
  "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY2ZDA4NWY2LTI1NzgtNDViZi1hYTE0LTQxYzE3NDU3ZDE0YiIsImlhdCI6MTc0Nzg1Mzg0MSwiZXhwIjoxNzQ3ODU3NDQxfQ.TAsn52-jNal1LnnDU_UDxG8jdiit3Z_N3Lt1auKFAhE"
}
