export enum EnvEnum {
  PORT = 'PORT',
  BROKER_PORT = "BROKER_PORT",
  DATABASE_URL = 'DATABASE_URL',
  PASSWORD_SALT_ROUNDS = 'PASSWORD_SALT_ROUNDS',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',
}
